// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN2YM6R-Hgmu8omvLjk8sRwFmm5EiP6mg',
    appId: '1:275672045435:web:3e636b7ab1ddc6caaf8fde',
    messagingSenderId: '275672045435',
    projectId: 'flutter-auth-app-1d2cf',
    authDomain: 'flutter-auth-app-1d2cf.firebaseapp.com',
    storageBucket: 'flutter-auth-app-1d2cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5yqnMLsidAn4y0qq-CWc8snMSwM-DsN0',
    appId: '1:275672045435:android:f31deb283f408970af8fde',
    messagingSenderId: '275672045435',
    projectId: 'flutter-auth-app-1d2cf',
    storageBucket: 'flutter-auth-app-1d2cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimaKfRajbOoAEtGadrv4XL0eGBUem80k',
    appId: '1:275672045435:ios:77500944a2ef0005af8fde',
    messagingSenderId: '275672045435',
    projectId: 'flutter-auth-app-1d2cf',
    storageBucket: 'flutter-auth-app-1d2cf.firebasestorage.app',
    iosBundleId: 'com.example.medallaFlutter',
  );
}
